Validating if options is really set in $scope
Validates if options is really set in $scope, otherwise it will throw an error like:

TypeError: Cannot read property 'initDate' of undefined
    at link (http://localhost:3000/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:1523:19)
    at http://localhost:3000/bower_components/angular/angular.js:8252:44
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8258:9)